name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  check:
    outputs:
      status: ${{ steps.early.conclusion }}
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["test"]'
      - name: See result
        run: echo" ${{ steps.check_pr_labels.outputs.result}}"
      - name: result
        if: ${{ steps.check_pr_labels.outputs.result  == 'fail' }}
        run: exit 1

  build:
    needs: check
    if: needs.check.outputs.status == 'success'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
